# Chirpy Configuration
lang: en
timezone: America/Chicago
title: Mason Kotlarz
tagline: Cybersecurity Engineering Portfolio
description: >-
  Portfolio showcasing projects and reflections in cybersecurity, 
  digital forensics, and software development.

# Chirpy theme
remote_theme: cotes2020/jekyll-theme-chirpy

# Site build settings
permalink: /posts/:title/
paginate: 10
paginate_path: /page:path/

# Social media
twitter:
  username: 
github:
  username: MasonKotlarz

# Comments (disable if not needed)
comments:
  active: false

# Analytics (disable if not needed)
analytics:
  active: false

# Exclude from processing
exclude:
  - .git
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock