title: "Mason Kotlarz Portfolio"
description: "Cybersecurity Engineering Portfolio"
baseurl: ""
url: "https://masonkotlarz.github.io"

# Use minimal theme
theme: minima

# Or no theme with custom layout
# theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path/
  reflections:
    output: true
    permalink: /reflections/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "reflections"
    values:
      layout: "default"