# =====================================================
# Site Settings
# =====================================================
title: "Mason Kotlarz Portfolio"
description: "Cybersecurity | Projects | Reflections"
url: ""   # leave empty for localhost, set to your GitHub Pages URL later
baseurl: ""  

# =====================================================
# Author Settings
# =====================================================
authors:
  mkotlarz:
    name: "Mason Kotlarz"
    avatar: /assets/img/profile.png
    bio: "Cybersecurity Engineering Student @ Iowa State"
    email: "maskotlarz@iastate.edu"
    github: "MasonKotlarz"
    linkedin: "https://linkedin.com/in/masonkotlarz"

# Default author
author: mkotlarz

# =====================================================
# Sidebar Settings
# =====================================================
avatar: /assets/img/profile.png

social:
  email: "maskotlarz@iastate.edu"
  github: "MasonKotlarz"
  linkedin: "https://linkedin.com/in/masonkotlarz"

# =====================================================
# Theme Settings
# =====================================================
theme: jekyll-theme-chirpy
lang: en
timezone: America/Chicago

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Feed
feed:
  path: feed.xml


# Define collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  reflections:
    output: true
    permalink: /reflections/:name/
  experience:
    output: true
    permalink: /experience/:name/
  tabs:
    output: true
    permalink: /:name/



# Defaults for layouts
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
  - scope:
      path: ""
      type: reflections
    values:
      layout: post
  - scope:
      path: ""
      type: experience
    values:
      layout: post
