# ─────────────────────────────────────────────
# Basic site settings
# ─────────────────────────────────────────────
title: "Mason Kotlarz"
description: "CPRE 494 Portfolio — Projects, Resume, and Reflections"
url: "https://mason-kotlarz.github.io"
baseurl: "" # leave blank for user.github.io root sites

# ─────────────────────────────────────────────
# Author info
# ─────────────────────────────────────────────
author:
  name: "Mason Kotlarz"
  email: "your_email@iastate.edu"
  avatar: "/assets/images/me.jpg" # headshot
  bio: "Computer Engineering student passionate about embedded systems, cybersecurity, and network defense."

# ─────────────────────────────────────────────
# Theme settings (Chirpy)
# ─────────────────────────────────────────────
theme: jekyll-theme-chirpy
lang: "en"
timezone: "America/Chicago"
plugins:
  - jekyll-feed

# ─────────────────────────────────────────────
# Collections — custom project pages
# ─────────────────────────────────────────────
collections:
  projects:
    output: true
    permalink: /projects/:name/

# ─────────────────────────────────────────────
# Defaults — layouts for pages and collections
# ─────────────────────────────────────────────
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

# ─────────────────────────────────────────────
# Build settings
# ─────────────────────────────────────────────
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ─────────────────────────────────────────────
# Navigation menu
# ─────────────────────────────────────────────
# These links appear in the site header/navbar
# ─────────────────────────────────────────────
nav:
  - title: "Home"
    url: "/"
  - title: "Resume"
    url: "/resume/"
  - title: "Projects"
    url: "/projects/"
  - title: "Reflections"
    url: "/reflections/"

# ─────────────────────────────────────────────
# Social links (optional)
# ─────────────────────────────────────────────
social:
  github: "mason-kotlarz"
  linkedin: "mason-kotlarz"
  email: "your_email@iastate.edu"

# ─────────────────────────────────────────────
# Exclude folders from build
# ─────────────────────────────────────────────
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github
  - .vscode
  - .devcontainer
  - tools

# ─────────────────────────────────────────────
# Feed / SEO / Sitemap configuration
# ─────────────────────────────────────────────
feed:
  path: feed.xml

seo:
  name: "Mason Kotlarz"
  type: "Person"

sitemap:
  exclude:
    - "/assets/"
    - "/node_modules/"

