title: "Mason Kotlarz Portfolio"
description: "Cybersecurity Engineering Portfolio"
baseurl: ""
url: "https://masonkotlarz.github.io"

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/
  reflections:
    output: true
    permalink: /reflections/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "reflections"
    values:
      layout: "default"
