# Chirpy Theme Configuration
lang: en
timezone: America/Chicago
title: Mason Kotlarz
tagline: Cybersecurity Engineering Portfolio
description: >-
  Portfolio showcasing projects and reflections in cybersecurity, 
  digital forensics, and software development.

# Chirpy theme
remote_theme: cotes2020/jekyll-theme-chirpy

# Site build settings
permalink: /posts/:title/
paginate: 10
paginate_path: /page:path/

# Social media (optional - fill with your info)
twitter:
  username: 
github:
  username: MasonKotlarz
linkedin:
  username: 

# Comments (optional)
comments:
  active: 
  provider: 

# Analytics (optional)
analytics:
  provider: 
  google:
    tracking_id: 