title: "Mason Kotlarz Portfolio"
description: "Cybersecurity Engineering Portfolio"
baseurl: ""
url: "https://masonkotlarz.github.io"

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

lang: en
timezone: America/Chicago

sidebar:
  avatar: /assets/img/profile.jpg
  title: "Mason Kotlarz"
  subtitle: "Cybersecurity Engineering Student"
  
  social:
    email: "mkotlarz@iastate.edu"
    linkedin: "https://linkedin.com/in/masonkotlarz"
    github: "https://github.com/MasonKotlarz"

# Define collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  reflections:
    output: true
    permalink: /reflections/:name/
  experience:
    output: true
    permalink: /experience/:name/
  tabs:
    output: true
    permalink: /:name/

author:
  name: "Mason Kotlarz"
  email: "youremail@domain.com"

# Defaults for layouts
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: post
  - scope:
      path: ""
      type: reflections
    values:
      layout: post
  - scope:
      path: ""
      type: experience
    values:
      layout: post
