title: "Mason Kotlarz Portfolio"
description: "Cybersecurity Engineering Portfolio"
baseurl: ""
url: "https://masonkotlarz.github.io"

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

sidebar:
  avatar: /assets/img/profileimg.jpg
  title: "Mason Kotlarz"
  subtitle: "Cybersecurity Engineering Student"
  description: maskotlarz@iastate.edu 

  # Add links for contact
  social:
    github: MasonKotlarz
    linkedin: your-linkedin-username
    email: your-email@iastate.edu


collections:
  projects:
    output: true
    permalink: /projects/:path/
  reflections:
    output: true
    permalink: /reflections/:path/
  experience:
    output: true
    permalink: /experience/:path/


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "reflections"
    values:
      layout: "default"
